// Extracts the Chu sprite frames into a compact pixel grid so p5 can REDRAW her
// procedurally (rect per cell) instead of blitting PNGs. Output: lib/chu-frames.ts
//
//   palette: 0 transparent · 1 white · 2 black · 3 grey
//
// Frames are aligned bottom-left in a shared grid so she stays grounded and the
// body doesn't jitter while the head/paw/tail move.

import { PNG } from "pngjs"
import fs from "node:fs"
import path from "node:path"

const DIR = path.resolve("public/chu")
const IDLE = [1, 2, 3, 4].map((i) => `idle_${i}.png`)
const LICK = Array.from({ length: 12 }, (_, i) => `lick_${i + 1}.png`)
const ALL = [...IDLE, ...LICK]

const H = 64            // target grid rows
const TARGET_H = 60     // cat height in cells (per-frame normalised → stable size)
const ALPHA_T = 40      // alpha threshold for "solid"

function load(file) {
  const buf = fs.readFileSync(path.join(DIR, file))
  const png = PNG.sync.read(buf)
  return png // {width,height,data:RGBA}
}

function bbox(png) {
  const { width: w, height: h, data } = png
  let minX = w, minY = h, maxX = -1, maxY = -1
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const a = data[(y * w + x) * 4 + 3]
      if (a > ALPHA_T) {
        if (x < minX) minX = x
        if (x > maxX) maxX = x
        if (y < minY) minY = y
        if (y > maxY) maxY = y
      }
    }
  }
  return { minX, minY, maxX, maxY, bw: maxX - minX + 1, bh: maxY - minY + 1 }
}

const pngs = ALL.map(load)
const boxes = pngs.map(bbox)
// per-frame scale by HEIGHT so the cat is the same size in every frame (the
// sitting silhouette height is stable; only the paw/head/tail move)
const scales = boxes.map((b) => TARGET_H / b.bh)
const W = Math.ceil(Math.max(...boxes.map((b, i) => b.bw * scales[i]))) + 1

function classify(r, g, b) {
  const lum = 0.299 * r + 0.587 * g + 0.114 * b
  if (lum < 95) return "2"   // black (mask / ear tips / tail tip / outline)
  if (lum > 170) return "1"  // white body
  return "3"                 // grey transitions
}

// Sample one grid frame, normalised to TARGET_H, anchored bottom-left.
function gridOf(png, box, scale) {
  const { width: w, data } = png
  const sw = box.bw * scale                 // scaled content width in cells
  const sh = TARGET_H                        // scaled content height in cells
  const topRow = H - sh                      // bottom aligned (small top margin)
  const srcPerCell = box.bh / TARGET_H       // source px per grid cell
  const rows = []
  for (let gy = 0; gy < H; gy++) {
    let row = ""
    for (let gx = 0; gx < W; gx++) {
      const u = gx / Math.max(1, sw)             // 0..1 across content, left aligned
      const v = (gy - topRow) / Math.max(1, sh)
      if (u < 0 || u >= 1 || v < 0 || v >= 1) { row += "0"; continue }
      const sx0 = box.minX + u * box.bw
      const sy0 = box.minY + v * box.bh
      let rr = 0, gg = 0, bb = 0, aa = 0, n = 0
      const step = Math.max(1, Math.floor(srcPerCell / 3))
      for (let dy = 0; dy < srcPerCell; dy += step) {
        for (let dx = 0; dx < srcPerCell; dx += step) {
          const sx = Math.floor(sx0 + dx)
          const sy = Math.floor(sy0 + dy)
          if (sx < 0 || sy < 0 || sx >= w || sy >= png.height) continue
          const idx = (sy * w + sx) * 4
          const a = data[idx + 3]
          aa += a
          if (a > ALPHA_T) { rr += data[idx]; gg += data[idx + 1]; bb += data[idx + 2]; n++ }
        }
      }
      const cells = Math.max(1, Math.ceil(srcPerCell / step) ** 2)
      const avgA = aa / cells
      if (avgA < 110 || n === 0) { row += "0"; continue }
      row += classify(rr / n, gg / n, bb / n)
    }
    rows.push(row)
  }
  return rows
}

const idleFrames = IDLE.map((f, i) => gridOf(pngs[i], boxes[i], scales[i]))
const lickFrames = LICK.map((f, i) => gridOf(pngs[IDLE.length + i], boxes[IDLE.length + i], scales[IDLE.length + i]))

const out = `// AUTO-GENERATED by scripts/extract-chu.mjs — do not edit by hand.
// Chu redrawn procedurally: each string row is one grid line, chars are palette
// indices (0 transparent · 1 white · 2 black · 3 grey). p5 draws a rect per cell.
export const CHU_W = ${W}
export const CHU_H = ${H}
export const CHU_IDLE: string[][] = ${JSON.stringify(idleFrames)}
export const CHU_LICK: string[][] = ${JSON.stringify(lickFrames)}
`
fs.writeFileSync(path.resolve("lib/chu-frames.ts"), out)
console.log(`wrote lib/chu-frames.ts  grid=${W}x${H}  idle=${idleFrames.length} lick=${lickFrames.length}`)
